version: 2
jobs:
  build:
    machine: true
      # Use an image with kernel 4.8+, which supports the binfmt_misc `F`
      # flag required for cross-building docker images without adding qemu
      # to the image itself.
      # https://www.kernel.org/doc/html/latest/admin-guide/binfmt-misc.html

      # Available images are listed here:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      #image: circleci/classic:201808-01

    steps:
      - checkout
      - run:
          name: intall deps
          command:  sudo -u root apt-get install libbox2d-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
 
      - run:
          name: Compile
          command: export TERM=xterm; make
   
