version: 2
jobs:
  build:
    docker:
        - image: eoshep/build-essentials:bionic
        
    steps:
      - checkout
      - run:
          name: deps
          command: apt-get update && apt-get install -y build-essential libasound2-dev libfreetype6-dev libbox2d-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - run:
          name: compile
          command: export TERM=xterm; make
